#Name: gin-chat
#Url: http://127.0.0.1:9050
#Mode: debug      # debug, release, test
#JwtSecret: TQ2MNWIB2zK0z9JCqUC6WcTG9pMTnX12CLuVSop5Xr2owx4M9JTJIzBnMMYeWwRs
#JwtTimeout: 86400
#Debug: true
#Proxy: false
#
#HTTP:
#  Addr: :9050
#  ReadTimeout: 5s
#  WriteTimeout: 5s
#
#Websocket:
#  Addr: :9060
#  ReadTimeout: 5s
#  WriteTimeout: 5s
