default:
  Addr: containers-us-west-59.railway.app:7472
  Password: "LBexXkYx47thaliYf5Fr"
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 100
  PoolTimeout: 240s
  Trace: true
